### ISSUE TITLE
CUDNN_jll conflict with Reactant

### ISSUE THREAD

**Issue by goulf-3m** [EnzymeAD/Reactant.jl#1465]
In a test project with this:

```
using Reactant
using Lux
using LuxCUDA
```

Precompiling this project errors with:

```
Failed to precompile test [e061e0cf-51c1-4f7f-bc1b-3df52df7b1b7] to "/home/goulf/.julia/compiled/v1.11/test/jl_3TaEDK".
ERROR: LoadError: InitError: could not load library "/home/goulf/.julia/artifacts/2eb570b35b597d106228383c5cfa490f4bf538ee/lib/libcudnn
_cnn.so"
/home/goulf/.julia/artifacts/2eb570b35b597d106228383c5cfa490f4bf538ee/lib/libcudnn_cnn.so: undefined symbol: _ZTVN5cudnn7backend25Expan
dBandMatrixOperationE, version libcudnn_graph.so.9
```

With this (reording):

```
using Lux
using LuxCUDA
using Reactant
```

Precompilation succeeds!

**Comment by avik-pal** [comment]
We are probably shipping a binary with different version of cudnn compared to CUDNN.jl.

Any particular reason, you need to load both in the same session?

**Comment by goulf-3m** [comment]
When I want to compare Lux+Reactant+Enzyme and Lux+LuxCUDA+Zygote a single script.

If using standard CUDNN_jll is achievable for Reactant, shipping another should be avoided.
If not achievable, rename those libs (and symbols?) to avoid collision is more user-friendly. (Of course, lower priority compared to Reactant's core functionality)

**Comment by giordano** [comment]
What's your version of `CUDNN_jll`? What's the value of `Reactant_jll.host_platform`?

**Comment by goulf-3m** [comment]
CUDNN_jll: maybe v9.10.0+0
Reactant_jll.host_platform: Linux x86_64 {cuda_version=12.6, cxxstring_abi=cxx11, gpu=cuda, julia_version=1.11.6, libc=glibc, libgfortran_version=5.0.0, libstdcxx_version=3.4.30, mode=opt}

The CUDNN_jll is 'maybe', because I failed to easily create a new minimal environment to verify (because downloading Reactant artifacts is very slow and fails frequently, compared to other Julia package artifacts).

**Comment by wsmoses** [comment]
this is now resolved for cuda 13+ with our newest jll. reopen if not
